### ISSUE TITLE
Fehler bei der Aktualisierung

### ISSUE THREAD

**Issue by Gruzelwuzel** [jprangenbergde/moneymoney-parqet#2]
Hallo,
ich bekomme beim Abruf eines öffentliches Depots derzeit die beigefügte Fehlermeldung. Bei anderen Depots des selben Zugangs geht es aber noch problemlos?

![Attachment](https://user-images.githubusercontent.com/76258453/164673741-cbc7e107-faa5-40b8-ba6c-e3cd7a6214c6.png)

**Comment by pballhausen** [comment]
Das Problem besteht seit der Einführung weiterer Assetsklassen bei Parqet. In einem Crypto Objekt gibt es "securitiy" nicht, weshalb es zu diesem Fehler kommt.

@jprangenbergde Besteht Interesse an einem PR? qie willst du mit diesem Projekt generell zukünftig umgehen? willst du es umbenennen zu Parqet? Wenn du kein Interesse an einer Fortführung hast, dann würde ich es Forken und die Benennung, aber auch die Anpassungen in einem anderen Repo durchführen.

**Comment by jprangenbergde** [comment]
@pballhausen Wir können das Repository umbenennen und du contributest die Anpassungen?

**Comment by pballhausen** [comment]
@jprangenbergde Sehr gern!

**Comment by pballhausen** [comment]
@jprangenbergde PR erstellt. Guck gern drüber und änder alles was du willst :)

**Comment by jprangenbergde** [comment]
@Gruzelwuzel: Sollte jetzt gefixed sein.

**Comment by Gruzelwuzel** [comment]
Super, danke! Funktioniert perfekt.
